---
- hosts: all
  become: yes
  become_method: sudo
  remote_user: bench

  tasks:
  
  - name: Ensure group "bench" exists
    ansible.builtin.group:
      name: bench
      state: present

  - name: Add the user 'bench' with admin permissions
    ansible.builtin.user:
      name: bench
      comment: Bench user to run benchmark
      password: "{{ 'bench' | password_hash('sha512','A512') }}"
      shell: /bin/bash
      groups: sudo,bench
      append: yes

  - name: Change file ownership, group and permissions
    ansible.builtin.file:
      path: /opt
      owner: bench
      group: sudo
      mode: '0770'
      recurse: yes

  - name: Update and upgrade apt packages
    become: true
    ansible.builtin.apt:
      upgrade: yes
      update_cache: yes
      cache_valid_time: 86400

  - name: Install Apache2
    become: true
    ansible.builtin.apt:
      name: apache2 
      state: latest
  
  - name: Install nginx
    become: true
    ansible.builtin.apt:
      name: nginx
      state: latest 

  - name: Install pyenv deps
    become: true
    ansible.builtin.apt:
      pkg: 
        - make
        - acl
        - build-essential
        - libssl-dev
        - zlib1g-dev
        - libbz2-dev
        - libreadline-dev
        - libsqlite3-dev
        - wget
        - curl
        - llvm
        - libncurses5-dev
        - xz-utils
        - tk-dev
        - libffi-dev
        - liblzma-dev
        - python-openssl
        - git
      state: latest

  - name: Clone pyenv repo
    git:
      repo: https://github.com/pyenv/pyenv.git
      dest: /usr/bin/.pyenv
      version: master
      update: yes

  - name: Clone Virtualenv repo
    git:
      repo: https://github.com/pyenv/pyenv-virtualenv.git 
      dest: /usr/bin/.pyenv/plugins/pyenv-virtualenv
      version: master
      update: yes

  - name: Add path etc to .bashrc.
    lineinfile:
      dest: /home/bench/.bashrc
      state: present
      create: yes
      line: "{{ item }}"
    with_items:
      - 'export PYENV_ROOT="/usr/bin/.pyenv"'
      - 'export PATH="$PYENV_ROOT/bin:$PATH"'
      - 'eval "$(pyenv init -)"'
      - 'eval "$(pyenv virtualenv-init -)"'

  - name: Ensure .pyenv permissions are set properly
    ansible.builtin.file: 
      path: /usr/bin/.pyenv
      state: directory
      recurse: yes
      mode: '0755'

  - name: Install python 3.10.4
    become: yes
    ansible.builtin.shell: PYTHON_CONFIGURE_OPTS="--enable-shared" /usr/bin/.pyenv/bin/pyenv install 3.10.4
    args:
      executable: /bin/bash

  - name: Copy files into /home/bench
    ansible.builtin.copy:
      src: "{{ item.src }}"
      dest: "{{ item.dest }}"
      mode: "{{item.mode}}"
      owner: bench
      group: bench
    with_items:
      - { src: './setup.sh', dest: '/home/bench/setup.sh', mode: '0555'}
      - { src: './flask-example/dist/flask_example-0.1.0-py3-none-any.whl', dest: '/home/bench/dist/', mode: '0777'}
      - { src: './fastapi-example/dist/fastapi_example-0.1.0-py3-none-any.whl', dest: '/home/bench/dist/', mode: '0777'}

  - name: Change directory, group and permissions
    ansible.builtin.file:
      path: "{{ item.dir }}"
      state: directory
      recurse: yes
      mode: '0755'
    with_items:
      - { dir: '/opt/lib'}
      - { dir: '/opt/bin'}
      - { dir: '/opt/src'}
